apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-stream.fullname" . }}
  labels:
    {{- include "video-stream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    {{- include "video-stream.selectorLabels" . | nindent 4 }}
