apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-user
  template:
    metadata:
      labels:
        app: video-user
    spec:
      containers:
        - name: video-user-container
          image: registry.cn-hangzhou.aliyuncs.com/offersmaker/video_user:latest
          ports:
            - containerPort: 9001
              protocol: TCP
      imagePullSecrets:
        - name: offermaker
